apiVersion: v1
data:
  MAINTENANCE: "false"
  NODE_ENV: production
  SERVER: flynn
  INDEX_FILE: index-testing
  CLIENT_DOMAIN: staging.boxxerworld.com
  ADMIN_DOMAIN: staging-admin.boxxerworld.com
  CDN_DOMAIN: cdn2.boxxerworld.com
kind: ConfigMap
metadata:
  name: boxxer-client-testing
  namespace: default
